### ISSUE TITLE
Updates to the tripal_vocab table.

### ISSUE THREAD

**Issue by spficklin** [tripal/t4d8#61] opened 2020-06-25 20:51 UTC
To be backwards compatible with the `tripal_get_term_details` API function the tripal_vocab tables need the `url` and `urlprefix` columns.

**Comment by spficklin** [comment] 2020-06-25 21:29
Wait... this may not be the case.  Hold off on fixing this until I get through issue #26

**Comment by laceysanderson** [comment] 2020-12-24 16:20
Now a duplicate of #81

**Closed as completed by laceysanderson** 2020-12-24 16:20 UTC
